image: node:16

stages:
  - security
  - build
  - test
  - pages

.install:
  before_script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm config set store-dir .pnpm-store
    - pnpm install --frozen-lockfile
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

audit:
  stage: security
  extends: .install
  script: pnpm audit --audit-level=critical

build:
  stage: build
  extends: .install
  script:
    - pnpm run build

unit-test:
  stage: test
  extends: .install
  script:
    - pnpm run test:ci

